# Generated by Django 4.2.4 on 2024-04-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[("heart_rate", "Heart Rate")], max_length=100
                    ),
                ),
                ("time", models.DateTimeField()),
                ("value", models.FloatField()),
            ],
        ),
    ]
